tags:
  - name: index
    description: Index routes
  - name: user
    description: User routes
  - name: to do
    description: To do routes
paths:
  /todo/create:
    post:
      tags:
        - to do
      summary: Creates a to do
      description: Creates a to dby giving parameters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/todo'
      responses:
        200:
          description: Successful operation
        

components:
  schemas:
    todo:
      type: object
      properties:
        name:
          type: string
          description: Name of the To Do
          example: house cleaning
        description:
          type: string
          description: The whole description of the To do
          example: mob the floors of upstairs
        isDone:
          type: boolean
