tags:
  - name: index
    description: Index routes
  - name: user
    description: User routes
  - name: to do
    description: To do routes
paths:
  /todo/create:
    post:
      tags:
        - to do
      summary: Creates a to do
      description: Creates a to do by giving parameters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/todo'
      responses:
        200:
          description: Successful operation
  /todo/{id}:
    get:  
      tags:   
        - to do 
      summary: Find to do by ID
      parameters:
        - name: id
          in: path
          description: ID of the to do to return 
          required: true
          schema:
            type: string
            example: 663aa81ebe6c895b819763bc
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todo'
        400:
          description: Not Found  
components:
  schemas:
    todo:
      type: object
      properties:
        name:
          type: string
          description: Name of the To Do
          example: house cleaning
        description:
          type: string
          description: The whole description of the To do
          example: mob the floors of upstairs
        isDone:
          type: boolean
